# Generated by Django 2.0.6 on 2018-06-20 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('isin_code', models.CharField(max_length=12)),
                ('edinet_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='security',
            name='security_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.SecurityCode'),
        ),
    ]
