# Generated by Django 2.0.6 on 2018-06-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='securitycode',
            name='code',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
