# Generated by Django 2.0.6 on 2018-06-24 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_auto_20180621_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='dividend',
            field=models.FloatField(verbose_name='1株配当'),
        ),
    ]
