# Generated by Django 2.0.6 on 2018-06-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_auto_20180624_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='date',
            field=models.DateField(db_index=True, null=True, verbose_name='日付'),
        ),
        migrations.AlterIndexTogether(
            name='security',
            index_together={('security_code', 'date')},
        ),
    ]
