# Generated by Django 2.0.6 on 2018-06-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_auto_20180627_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitycode',
            name='display_name',
            field=models.CharField(default='dummy', max_length=1024, verbose_name='画面表示用銘柄名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='securitycode',
            name='code',
            field=models.CharField(db_index=True, max_length=4, unique=True, verbose_name='証券コード'),
        ),
        migrations.AlterField(
            model_name='securitycode',
            name='edinet_code',
            field=models.CharField(db_index=True, max_length=6, verbose_name='EDINETコード'),
        ),
        migrations.AlterIndexTogether(
            name='securitymargin',
            index_together={('security_code', 'date')},
        ),
        migrations.AlterIndexTogether(
            name='securityprice',
            index_together={('security_code', 'date')},
        ),
    ]
